version: 3.1.{build}
image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
install:
  - ps: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
  - ps: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
  - ps: Install-Module InvokeBuild
build_script:
  - ps: Invoke-Build
artifacts:
  - path: artifacts/**.nupkg
    name: NuGet
clone_depth: 1
test: off
deploy: off