version: 2.2.{build}
init:
  - git config --global core.autocrlf true
install:
  - ps: inmo InvokeBuild
build_script:
  - ps: Invoke-Build
artifacts:
  - path: artifacts/**.nupkg
    name: NuGet
clone_depth: 1
test: off
deploy: off